-- Dharohar AI — Multi-State Heritage Seed Data

-- Insert 8 supported states
INSERT INTO supported_states (name, code, region, description, is_primary, display_order) VALUES
('Gujarat', 'GJ', 'West', 'Rich cultural heritage spanning Indus Valley Civilization to modern India. Known for temples, stepwells, textiles, and folk traditions.', TRUE, 1),
('Rajasthan', 'RJ', 'North', 'Land of kings with magnificent forts, palaces, desert culture, and vibrant folk traditions.', FALSE, 2),
('Punjab', 'PB', 'North', 'Land of five rivers with rich Sikh heritage, Mughal architecture, and vibrant cultural traditions.', FALSE, 3),
('Goa', 'GA', 'West', 'Former Portuguese colony with unique blend of Indian and European cultural heritage.', FALSE, 4),
('Tamil Nadu', 'TN', 'South', 'Ancient Dravidian civilization with magnificent temples, classical arts, and literary traditions.', FALSE, 5),
('Maharashtra', 'MH', 'West', 'Maratha heritage with historic forts, caves, and diverse cultural traditions.', FALSE, 6),
('Madhya Pradesh', 'MP', 'Central', 'Heart of India with UNESCO World Heritage sites, tribal art, and ancient temple architecture.', FALSE, 7),
('Delhi', 'DL', 'North', 'Capital territory with layers of history from Delhi Sultanate to Mughal Empire to modern India.', FALSE, 8)
ON CONFLICT (code) DO NOTHING;

-- Gujarat Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('GJ', 'Rani ki Vav', 'monument', 'Patan', 'Medieval (11th century)', 'A UNESCO World Heritage stepwell in Patan, Gujarat. Built by Queen Udayamati in memory of her husband Bhima I. Features over 1,500 sculptures across seven levels.', 'One of the most ornate stepwells in India and a masterpiece of Maru-Gurjara architecture. Featured on the Indian 100 rupee note.', 'Construction attributed to the Solanki period', 'Queen Udayamati, Bhima I', 'Patola weaving of Patan', ARRAY['stepwell','patan','UNESCO','solanki','queen'], ARRAY['Rani ki Vav','Queen Stepwell','Rani no Havalo'], ARRAY['Tell me about Rani ki Vav','Why is Rani ki Vav important','What is the stepwell at Patan','History of Rani ki Vav Patan'], 'UNESCO World Heritage List'),
('GJ', 'Modhera Sun Temple', 'monument', 'Modhera', 'Medieval (11th century)', 'A Hindu temple dedicated to the Sun God Surya, built by Bhima I of the Chaulukya dynasty in 1026 CE. Features a massive stepwell (Surya Kund) and intricately carved assembly hall.', 'One of the three major Sun temples in India. Demonstrates advanced astronomical knowledge and architectural brilliance of the Solanki era.', 'Built after Mahmud of Ghaznis invasion', 'Bhima I', NULL, ARRAY['sun temple','modhera','surya','solanki'], ARRAY['Modhera Sun Temple','Surya Mandir Modhera'], ARRAY['Tell me about Modhera Sun Temple','What is the Sun Temple at Modhera','History of Modhera Sun Temple'], 'Archaeological Survey of India'),
('GJ', 'Patola Silk', 'craft', 'Patan', 'Medieval to Present', 'Double ikat woven silk sari tradition from Patan. The intricate weaving process takes 4-6 months for a single sari. Only a few families in Patan still practice this ancient craft.', 'UNESCO Intangible Cultural Heritage nominee. The Patola sari was historically traded across Southeast Asia and was considered a status symbol.', NULL, NULL, 'Patola double ikat weaving', ARRAY['patola','silk','patan','ikat','weaving','textile'], ARRAY['Patola','Patola Silk','Patola Sari'], ARRAY['Tell me about Patola weaving','How is Patola silk made','Patola weaving in Patan'], 'Gujarat Tourism'),
('GJ', 'Adalaj Stepwell', 'monument', 'Ahmedabad', 'Medieval (1498)', 'An intricately carved five-story stepwell built in 1498 by Queen Rudabai, wife of Vaghela chief Mahamandaleshwar. Features Indo-Islamic architecture with Hindu and Jain motifs.', 'One of the finest examples of stepwell architecture in Gujarat. Demonstrates cultural synthesis between Hindu and Islamic artistic traditions.', NULL, 'Queen Rudabai', NULL, ARRAY['adalaj','stepwell','ahmedabad','vaghela'], ARRAY['Adalaj Ni Vav','Adalaj Stepwell'], ARRAY['Tell me about Adalaj Stepwell','History of Adalaj','Who built Adalaj Stepwell'], 'ASI'),
('GJ', 'Dholavira', 'monument', 'Kutch', 'Ancient (3000 BCE)', 'UNESCO World Heritage archaeological site of the Indus Valley Civilization. Features sophisticated water management system, a 10-letter signboard in Indus script, and advanced urban planning.', 'One of the five largest Harappan sites. Provides crucial evidence of the Indus Valley Civilizations urban planning and hydraulic engineering.', NULL, NULL, NULL, ARRAY['dholavira','indus','harappan','kutch','IVC'], ARRAY['Dholavira','Dholavira Harappan Site'], ARRAY['Tell me about Dholavira','What is Dholavira','Indus Valley site in Gujarat'], 'UNESCO'),
('GJ', 'Kutch Embroidery', 'craft', 'Kutch', 'Medieval to Present', 'Intricate hand embroidery tradition from the Kutch region, practiced by various communities including the Rabari, Ahir, and Jat communities. Features mirror work, beadwork, and vibrant thread colors.', 'Recognized as a Geographical Indication product. Represents the cultural diversity of Kutch with each community having distinct embroidery styles.', NULL, NULL, 'Kutchi mirror work embroidery', ARRAY['kutch','embroidery','mirror work','rabari','craft'], ARRAY['Kutch Embroidery','Kutchi Work','Kutch Mirror Work'], ARRAY['Tell me about Kutch embroidery','What crafts are famous in Kutch','Kutch mirror work'], 'GI Registry India'),
('GJ', 'Garba', 'tradition', 'Gujarat-wide', 'Medieval to Present', 'Traditional devotional dance performed during Navratri festival. Dancers move in concentric circles around a central lamp (Garbi) representing the divine feminine.', 'Iconic cultural tradition of Gujarat recognized globally. The largest Garba event is held at GMDC Ground in Ahmedabad during Navratri.', 'Navratri', NULL, NULL, ARRAY['garba','navratri','dance','gujarat','festival'], ARRAY['Garba','Dandiya Raas'], ARRAY['Tell me about Garba','What is Garba dance','Navratri celebration in Gujarat'], 'Gujarat Tourism'),
('GJ', 'Mahatma Gandhi', 'person', 'Porbandar', 'Modern (1869-1948)', 'Father of the Indian Nation. Born in Porbandar, Gujarat. Led Indias independence movement through non-violent civil disobedience. Lived and worked from Sabarmati Ashram in Ahmedabad.', 'Global icon of non-violence. Led the Salt March from Sabarmati Ashram to Dandi. His philosophy influenced civil rights movements worldwide.', 'Salt March (Dandi March) 1930', 'Mahatma Gandhi', NULL, ARRAY['gandhi','mahatma','sabarmati','porbandar','non-violence','dandi'], ARRAY['Mahatma Gandhi','Gandhiji','Bapu'], ARRAY['Tell me about Mahatma Gandhi','Gandhis connection to Gujarat','Sabarmati Ashram history'], 'Gandhi Ashram Trust');

-- Rajasthan Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('RJ', 'Amber Fort', 'monument', 'Jaipur', 'Medieval (16th century)', 'A majestic fortress-palace complex built by Raja Man Singh I in 1592. Features the Sheesh Mahal (Mirror Palace), Ganesh Pol gateway, and stunning views of Maota Lake.', 'One of the finest examples of Rajput military architecture. Blends Hindu and Mughal artistic styles.', NULL, 'Raja Man Singh I', NULL, ARRAY['amber','fort','jaipur','rajput','maharaja'], ARRAY['Amer Fort','Amber Palace'], ARRAY['Tell me about Amber Fort','History of Amber Fort Jaipur','Who built Amber Fort'], 'Rajasthan Tourism'),
('RJ', 'Hawa Mahal', 'monument', 'Jaipur', 'Medieval (1799)', 'Palace of Winds built by Maharaja Sawai Pratap Singh in 1799. Features 953 small windows (jharokhas) designed to allow royal women to observe street festivals without being seen.', 'Iconic symbol of Jaipur. The honeycomb facade is an architectural marvel designed to catch cool breezes.', NULL, 'Maharaja Sawai Pratap Singh', NULL, ARRAY['hawa mahal','jaipur','palace of winds','pink city'], ARRAY['Hawa Mahal','Palace of Winds'], ARRAY['Tell me about Hawa Mahal','Why is Hawa Mahal famous','Architecture of Hawa Mahal'], 'ASI'),
('RJ', 'Chokhi Dhani', 'tradition', 'Jaipur', 'Modern', 'A traditional Rajasthani village resort showcasing Rajasthani culture through folk dances, puppet shows, camel rides, and authentic cuisine.', 'Preserves and promotes traditional Rajasthani village life and cultural practices for visitors.', NULL, NULL, NULL, ARRAY['chokhi dhani','rajasthani culture','village','folk'], ARRAY['Chokhi Dhani'], ARRAY['Tell me about Rajasthani culture','Traditional village life in Rajasthan','Rajasthani folk traditions'], 'Rajasthan Tourism'),
('RJ', 'Blue Pottery', 'craft', 'Jaipur', 'Medieval to Present', 'Traditional Jaipur pottery known for its vivid blue glaze. Uses quartz stone powder instead of clay. The technique was introduced during Mughal era and perfected in Jaipur.', 'A distinctive Jaipur craft that has become synonymous with the citys artistic identity. Recognized as a GI product.', NULL, NULL, 'Blue pottery of Jaipur', ARRAY['blue pottery','jaipur','ceramics','craft'], ARRAY['Jaipur Blue Pottery','Blue Pottery'], ARRAY['Tell me about Blue Pottery','How is blue pottery made','Famous crafts of Jaipur'], 'GI Registry India');

-- Punjab Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('PB', 'Golden Temple', 'monument', 'Amritsar', 'Modern (16th-19th century)', 'Also known as Sri Harmandir Sahib. The holiest Gurdwara of Sikhism, built in the 16th century and plated with gold by Maharaja Ranjit Singh. Surrounded by the sacred Amrit Sarovar (Pool of Nectar).', 'The most important pilgrimage site of Sikhism. Serves free meals (langar) to over 100,000 people daily regardless of religion.', 'Founded by Guru Ram Das, completed by Guru Arjan Dev', 'Guru Arjan Dev, Maharaja Ranjit Singh', NULL, ARRAY['golden temple','harmandir','amritsar','sikh','gurdwara'], ARRAY['Sri Harmandir Sahib','Golden Temple','Harmandir Sahib'], ARRAY['Tell me about Golden Temple','History of Harmandir Sahib','Why is Golden Temple important'], 'SGPC'),
('PB', 'Jallianwala Bagh', 'monument', 'Amritsar', 'Modern (1919)', 'A public garden and memorial site where British troops under General Dyer massacred hundreds of unarmed civilians on April 13, 1919. The bullet marks are still visible on the walls.', 'A pivotal event in Indias independence movement. The massacre galvanized the freedom struggle and led to the Jallianwala Bagh Massacre investigation.', 'Jallianwala Bagh Massacre 1919', 'General Dyer, Rabindranath Tagore', NULL, ARRAY['jallianwala bagh','amritsar','massacre','1919','independence'], ARRAY['Jallianwala Bagh','Bagh Jallianwala'], ARRAY['Tell me about Jallianwala Bagh','What happened at Jallianwala Bagh','History of 1919 Amritsar massacre'], 'ASI'),
('PB', 'Bhangra', 'tradition', 'Punjab-wide', 'Medieval to Present', 'Traditional folk dance of Punjab performed during harvest festivals, especially Vaisakhi. Energetic dance with distinctive shoulder movements and music played on the dhol drum.', 'Symbol of Punjabi cultural identity and joy. Now popular worldwide as a form of music and dance.', 'Vaisakhi harvest festival', NULL, 'Dhol drumming', ARRAY['bhangra','punjab','dance','vaisakhi','harvest','dhol'], ARRAY['Bhangra','Punjabi Bhangra'], ARRAY['Tell me about Bhangra','What is Bhangra dance','Punjabi harvest festival dance'], 'Punjab Tourism'),
('PB', 'Phulkari', 'craft', 'Punjab-wide', 'Medieval to Present', 'Traditional embroidery art of Punjab. Women create vibrant floral patterns on shawls and dupattas using long darning stitches. Traditionally made by mothers for daughters.', 'A GI-tagged craft representing Punjabi women creativity and cultural traditions. Patterns encode social messages and family stories.', NULL, NULL, 'Phulkari embroidery', ARRAY['phulkari','embroidery','punjab','craft','textile'], ARRAY['Phulkari','Punjabi Phulkari'], ARRAY['Tell me about Phulkari','How is Phulkari made','Punjabi embroidery traditions'], 'GI Registry India');

-- Goa Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('GA', 'Basilica of Bom Jesus', 'monument', 'Old Goa', 'Colonial (16th century)', 'UNESCO World Heritage Church in Old Goa. Built in 1594. Houses the mortal remains of St. Francis Xavier. Exemplifies Baroque architecture in India.', 'One of the finest examples of Baroque architecture in India. Part of the Churches and Convents of Goa UNESCO World Heritage Site.', NULL, 'St. Francis Xavier, Baroque architecture', NULL, ARRAY['bom jesus','goa','church','old goa','UNESCO','francis xavier'], ARRAY['Basilica of Bom Jesus','Church of Bom Jesus'], ARRAY['Tell me about Basilica of Bom Jesus','Old Goa churches','St. Francis Xavier Goa'], 'UNESCO'),
('GA', 'Goa Carnival', 'festival', 'Panaji', 'Colonial to Present', 'Annual carnival celebration introduced by the Portuguese. Features colorful parades, music, dance, and float processions led by King Momo.', 'Unique cultural fusion of Indian and Portuguese traditions. One of the few carnival celebrations in Asia.', NULL, NULL, NULL, ARRAY['carnival','goa','festival','portuguese','king momo'], ARRAY['Goa Carnival','Carnival of Goa'], ARRAY['Tell me about Goa Carnival','What is the Goa Carnival','Portuguese festivals in Goa'], 'Goa Tourism'),
('GA', 'Feni', 'food', 'Goa', 'Colonial to Present', 'Traditional Goan spirit distilled from cashew apples or coconut. A protected Geographical Indication product of Goa.', 'Part of Goan culinary identity. Cashew feni production is a centuries-old tradition tied to Goas cashew cultivation.', NULL, NULL, 'Feni distillation', ARRAY['feni','goa','cashew','liquor','food'], ARRAY['Feni','Cashew Feni','Coconut Feni'], ARRAY['Tell me about Feni','What is Feni','Goan alcoholic beverages'], 'GI Registry India');

-- Tamil Nadu Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('TN', 'Meenakshi Amman Temple', 'monument', 'Madurai', 'Ancient to Medieval', 'Historic Hindu temple dedicated to Goddess Meenakshi (Parvati) and Lord Sundareshwar (Shiva). Features 14 gopurams (gateway towers) adorned with thousands of colorful sculptures.', 'One of the most important temples in Tamil Nadu. The temple complex covers 14 acres and is a masterpiece of Dravidian architecture.', NULL, NULL, NULL, ARRAY['meenakshi','madurai','temple','dravidian','gopuram'], ARRAY['Meenakshi Temple','Madurai Meenakshi Temple'], ARRAY['Tell me about Meenakshi Temple','History of Madurai temple','Dravidian temple architecture'], 'ASI'),
('TN', 'Bharatanatyam', 'tradition', 'Tamil Nadu-wide', 'Ancient to Present', 'Classical dance form originating in Tamil Nadu, one of the oldest classical dance traditions in India. Performed as a solo dance with elaborate hand gestures (mudras) and facial expressions.', 'UNESCO Intangible Cultural Heritage. The dance form dates back over 2,000 years and was traditionally performed in temples.', NULL, NULL, 'Bharatanatyam dance', ARRAY['bharatanatyam','dance','classical','madurai','temple dance'], ARRAY['Bharatanatyam','Bharata Natyam'], ARRAY['Tell me about Bharatanatyam','History of Bharatanatyam','Classical dances of Tamil Nadu'], 'UNESCO'),
('TN', 'Chola Bronzes', 'craft', 'Thanjavur', 'Medieval (9th-13th century)', 'Masterpiece bronze casting tradition of the Chola dynasty. The Nataraja (Dancing Shiva) bronze is considered one of the greatest achievements of Indian art.', 'UNESCO recognizes Chola bronzes as masterpieces. The lost-wax casting technique produced some of the finest metal sculptures in world art history.', NULL, 'Chola dynasty', 'Lost-wax bronze casting', ARRAY['chola','bronze','nataraja','thanjavur','sculpture'], ARRAY['Chola Bronzes','Nataraja','Chola Bronze Casting'], ARRAY['Tell me about Chola Bronzes','How are Chola bronzes made','Nataraja sculpture'], 'UNESCO');

-- Maharashtra Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('MH', 'Ajanta Caves', 'monument', 'Aurangabad', 'Ancient (2nd century BCE)', 'UNESCO World Heritage Buddhist cave complex featuring 30 rock-cut caves with exquisite paintings and sculptures. The paintings depict Jataka tales and Buddhist teachings.', 'One of the greatest artistic achievements of ancient India. The paintings are among the finest surviving examples of ancient Indian art.', NULL, NULL, NULL, ARRAY['ajanta','caves','aurangabad','buddhist','paintings','UNESCO'], ARRAY['Ajanta Caves','Ajanta Cave Paintings'], ARRAY['Tell me about Ajanta Caves','What is inside Ajanta Caves','Buddhist caves in Maharashtra'], 'UNESCO'),
('MH', 'Ellora Caves', 'monument', 'Aurangabad', 'Medieval (6th-10th century)', 'UNESCO World Heritage site with 34 rock-cut caves representing Buddhist, Hindu, and Jain traditions. The Kailasa Temple (Cave 16) is the largest monolithic rock excavation in the world.', 'Remarkable for its religious harmony. Three religions coexist side by side. The Kailasa Temple is an architectural marvel carved from a single rock.', NULL, NULL, NULL, ARRAY['ellora','caves','aurangabad','kailasa','UNESCO','monolithic'], ARRAY['Ellora Caves','Verul Caves'], ARRAY['Tell me about Ellora Caves','What is the Kailasa Temple','Rock-cut caves in Maharashtra'], 'UNESCO'),
('MH', 'Warli Art', 'craft', 'Thane', 'Ancient to Present', 'Tribal art form of the Warli people of the Sahyadri mountains. Uses white rice paste on mud walls to create geometric patterns depicting daily life, nature, and festivals.', 'One of the oldest art forms in India dating back to 2500 BCE. Recognized for its simplicity and storytelling power.', NULL, NULL, 'Warli painting', ARRAY['warli','tribal','art','thane','painting'], ARRAY['Warli Art','Warli Painting'], ARRAY['Tell me about Warli art','What is Warli painting','Tribal art of Maharashtra'], 'Maharashtra Tourism');

-- Madhya Pradesh Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('MP', 'Khajuraho Temples', 'monument', 'Khajuraho', 'Medieval (10th-11th century)', 'UNESCO World Heritage group of Hindu and Jain temples famous for their Nagara-style architecture and intricate erotic sculptures. Built by the Chandela dynasty.', 'A masterpiece of Indian temple architecture. The sculptures depict various aspects of human life, including spiritual and secular themes.', NULL, 'Chandela dynasty', NULL, ARRAY['khajuraho','temples','UNESCO','sculpture','chandela'], ARRAY['Khajuraho Temples','Khajuraho Group of Monuments'], ARRAY['Tell me about Khajuraho Temples','Why are Khajuraho Temples famous','Sculptures at Khajuraho'], 'UNESCO'),
('MP', 'Sanchi Stupa', 'monument', 'Sanchi', 'Ancient (3rd century BCE)', 'UNESCO World Heritage Buddhist monument. The Great Stupa was commissioned by Emperor Ashoka in the 3rd century BCE and is one of the oldest stone structures in India.', 'One of the oldest and best-preserved stupas in India. The four toranas (gateways) feature exquisite Buddhist narrative art.', NULL, 'Emperor Ashoka', NULL, ARRAY['sanchi','stupa','buddhist','ashoka','UNESCO'], ARRAY['Sanchi Stupa','Great Stupa Sanchi'], ARRAY['Tell me about Sanchi Stupa','History of Sanchi','Ashokas Buddhist monuments'], 'UNESCO'),
('MP', 'Gond Art', 'craft', 'Central MP', 'Traditional to Present', 'Traditional art form of the Gond tribal community. Uses vibrant colors and intricate dot patterns to depict nature, mythology, and daily life.', 'Recognized as a significant Indian tribal art form. The Gond style has gained international recognition through artists like Jangarh Singh Shyam.', NULL, NULL, 'Gond tribal painting', ARRAY['gond','tribal','art','painting','central india'], ARRAY['Gond Art','Gond Painting'], ARRAY['Tell me about Gond art','What is Gond painting','Tribal art of Madhya Pradesh'], 'MP Tourism');

-- Delhi Heritage Knowledge
INSERT INTO chatbot_knowledge (state_code, heritage_name, heritage_type, city, historical_period, description, significance, related_event, related_person, related_craft, keywords, aliases, chatbot_question_examples, source) VALUES
('DL', 'Red Fort', 'monument', 'New Delhi', 'Medieval (17th century)', 'UNESCO World Heritage Mughal fortress-palace built by Emperor Shah Jahan in 1638. Served as the main residence of Mughal emperors for nearly 200 years.', 'Symbol of Indian sovereignty. The Prime Minister hoists the national flag here on Independence Day. Masterpiece of Mughal architecture.', NULL, 'Shah Jahan', NULL, ARRAY['red fort','lal qila','delhi','mughal','UNESCO'], ARRAY['Red Fort','Lal Qila','Lal Quila'], ARRAY['Tell me about Red Fort','Who built the Red Fort','History of Red Fort Delhi'], 'UNESCO'),
('DL', 'Qutub Minar', 'monument', 'New Delhi', 'Medieval (12th century)', 'UNESCO World Heritage minaret standing 72.5 meters tall. Construction began in 1192 by Qutb-ud-Din Aibak and was completed by his successor Iltutmish.', 'Tallest brick minaret in the world. Demonstrates the early Indo-Islamic architectural style and the transition from Hindu to Islamic building traditions.', NULL, 'Qutb-ud-Din Aibak, Iltutmish', NULL, ARRAY['qutub minar','delhi','minaret','UNESCO','sultanate'], ARRAY['Qutub Minar','Qutb Minar'], ARRAY['Tell me about Qutub Minar','Who built Qutub Minar','History of Qutub Minar Delhi'], 'UNESCO'),
('DL', 'Chandni Chowk', 'tradition', 'Old Delhi', 'Medieval (17th century)', 'One of the oldest and busiest markets in Old Delhi, built by Mughal Emperor Shah Jahan. Famous for street food, spices, textiles, and traditional bazaars.', 'A living heritage market representing centuries of Delhi trading traditions. The narrow lanes contain some of the oldest shops and food stalls in Delhi.', NULL, 'Shah Jahan', NULL, ARRAY['chandni chowk','delhi','market','mughal','bazaar','food'], ARRAY['Chandni Chowk','Old Delhi Market'], ARRAY['Tell me about Chandni Chowk','What is Chandni Chowk','Old Delhi market traditions'], 'Delhi Tourism');
