/**
 * Heritage Atlas — Famous Heritage Markers
 *
 * Predefined famous heritage locations for all 8 supported states.
 * These supplement the database locations to ensure every state
 * has meaningful markers on the map.
 *
 * Coordinates are real geographic positions verified against public data.
 * These are used as supplemental markers alongside API-sourced database locations.
 */

export interface FamousMarker {
  id: string;
  name: string;
  state: string;
  stateCode: string;
  type: "state" | "site" | "city";
  category: string;
  description: string;
  latitude: number;
  longitude: number;
}

export const FAMOUS_HERITAGE_MARKERS: FamousMarker[] = [
  // ========== GUJARAT ==========
  {
    id: "fm-gj-patan-ranikivav",
    name: "Rani ki Vav",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "UNESCO World Heritage stepwell in Patan, built in the 11th century.",
    latitude: 23.8571,
    longitude: 72.1330,
  },
  {
    id: "fm-gj-modhera-suntemple",
    name: "Modhera Sun Temple",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "11th-century Sun Temple built during the Solanki dynasty.",
    latitude: 23.5866,
    longitude: 72.2317,
  },
  {
    id: "fm-gj-dholavira",
    name: "Dholavira",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "UNESCO World Heritage Indus Valley Civilization archaeological site.",
    latitude: 23.8858,
    longitude: 70.2172,
  },
  {
    id: "fm-gj-adalaj",
    name: "Adalaj Stepwell",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "Five-story Indo-Islamic stepwell built in 1498 near Ahmedabad.",
    latitude: 23.1663,
    longitude: 72.5774,
  },
  {
    id: "fm-gj-sabarmati",
    name: "Sabarmati Ashram",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "Mahatma Gandhi's historic ashram on the banks of the Sabarmati River.",
    latitude: 23.0609,
    longitude: 72.5797,
  },
  {
    id: "fm-gj-ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    stateCode: "GJ",
    type: "city",
    category: "city",
    description: "Former capital of Gujarat — historic old city, Sabarmati Ashram, and textile heritage.",
    latitude: 23.0225,
    longitude: 72.5714,
  },

  // ========== RAJASTHAN ==========
  {
    id: "fm-rj-amberfort",
    name: "Amber Fort",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "site",
    category: "monument",
    description: "Majestic fortress-palace complex in Jaipur, built in 1592.",
    latitude: 26.9855,
    longitude: 75.8513,
  },
  {
    id: "fm-rj-hawamahal",
    name: "Hawa Mahal",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "site",
    category: "monument",
    description: "Palace of Winds with 953 windows, built in 1799 in Jaipur.",
    latitude: 26.9239,
    longitude: 75.8267,
  },
  {
    id: "fm-rj-mehrangarh",
    name: "Mehrangarh Fort",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "site",
    category: "monument",
    description: "One of the largest forts in India, located in Jodhpur.",
    latitude: 26.2985,
    longitude: 73.0184,
  },
  {
    id: "fm-rj-jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "city",
    category: "city",
    description: "The Pink City — capital of Rajasthan with rich royal heritage.",
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    id: "fm-rj-udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "city",
    category: "city",
    description: "City of Lakes — known for Lake Palace, City Palace, and romantic setting.",
    latitude: 24.5854,
    longitude: 73.7125,
  },

  // ========== PUNJAB ==========
  {
    id: "fm-pb-goldentemple",
    name: "Golden Temple",
    state: "Punjab",
    stateCode: "PB",
    type: "site",
    category: "monument",
    description: "Sri Harmandir Sahib — the holiest Sikh shrine in Amritsar.",
    latitude: 31.6200,
    longitude: 74.8765,
  },
  {
    id: "fm-pb-jallianwala",
    name: "Jallianwala Bagh",
    state: "Punjab",
    stateCode: "PB",
    type: "site",
    category: "monument",
    description: "Memorial garden commemorating the 1919 Jallianwala Bagh massacre.",
    latitude: 31.6207,
    longitude: 74.8810,
  },
  {
    id: "fm-pb-amritsar",
    name: "Amritsar",
    state: "Punjab",
    stateCode: "PB",
    type: "city",
    category: "city",
    description: "Spiritual and cultural center of Sikhism — home to the Golden Temple.",
    latitude: 31.6340,
    longitude: 74.8723,
  },

  // ========== GOA ==========
  {
    id: "fm-ga-bomjesus",
    name: "Basilica of Bom Jesus",
    state: "Goa",
    stateCode: "GA",
    type: "site",
    category: "monument",
    description: "UNESCO World Heritage Baroque church in Old Goa, built in 1594.",
    latitude: 15.5009,
    longitude: 73.9115,
  },
  {
    id: "fm-ga-secathedral",
    name: "Sé Cathedral",
    state: "Goa",
    stateCode: "GA",
    type: "site",
    category: "monument",
    description: "Largest church in Asia — Portuguese-Manueline style cathedral in Old Goa.",
    latitude: 15.5013,
    longitude: 73.9128,
  },
  {
    id: "fm-ga-panaji",
    name: "Panaji",
    state: "Goa",
    stateCode: "GA",
    type: "city",
    category: "city",
    description: "Capital of Goa — known for Latin Quarter, churches, and Portuguese heritage.",
    latitude: 15.4989,
    longitude: 73.8278,
  },

  // ========== TAMIL NADU ==========
  {
    id: "fm-tn-meenakshi",
    name: "Meenakshi Amman Temple",
    state: "Tamil Nadu",
    stateCode: "TN",
    type: "site",
    category: "monument",
    description: "Dravidian masterpiece with 14 colorful gopurams in Madurai.",
    latitude: 9.9195,
    longitude: 78.1193,
  },
  {
    id: "fm-tn-mahabalipuram",
    name: "Mahabalipuram",
    state: "Tamil Nadu",
    stateCode: "TN",
    type: "site",
    category: "monument",
    description: "UNESCO Group of Monuments — rock-cut temples and shore temple.",
    latitude: 12.6168,
    longitude: 80.1992,
  },
  {
    id: "fm-tn-madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    stateCode: "TN",
    type: "city",
    category: "city",
    description: "Temple City — one of the oldest continuously inhabited cities in India.",
    latitude: 9.9252,
    longitude: 78.1198,
  },

  // ========== MAHARASHTRA ==========
  {
    id: "fm-mh-ajanta",
    name: "Ajanta Caves",
    state: "Maharashtra",
    stateCode: "MH",
    type: "site",
    category: "monument",
    description: "UNESCO Buddhist cave complex with ancient paintings near Aurangabad.",
    latitude: 20.5519,
    longitude: 75.7033,
  },
  {
    id: "fm-mh-ellora",
    name: "Ellora Caves",
    state: "Maharashtra",
    stateCode: "MH",
    type: "site",
    category: "monument",
    description: "UNESCO site with monolithic Kailasa Temple — the largest rock-cut structure.",
    latitude: 20.0267,
    longitude: 75.1792,
  },
  {
    id: "fm-mh-gateway",
    name: "Gateway of India",
    state: "Maharashtra",
    stateCode: "MH",
    type: "site",
    category: "monument",
    description: "Iconic arch monument in Mumbai, built to commemorate the 1911 royal visit.",
    latitude: 18.9220,
    longitude: 72.8347,
  },
  {
    id: "fm-mh-mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    stateCode: "MH",
    type: "city",
    category: "city",
    description: "Financial capital of India — Gateway of India, colonial architecture, and Bollywood.",
    latitude: 19.0760,
    longitude: 72.8777,
  },

  // ========== MADHYA PRADESH ==========
  {
    id: "fm-mp-khajuraho",
    name: "Khajuraho Temples",
    state: "Madhya Pradesh",
    stateCode: "MP",
    type: "site",
    category: "monument",
    description: "UNESCO Hindu and Jain temples famous for Nagara-style architecture.",
    latitude: 24.8319,
    longitude: 79.9200,
  },
  {
    id: "fm-mp-sanchi",
    name: "Sanchi Stupa",
    state: "Madhya Pradesh",
    stateCode: "MP",
    type: "site",
    category: "monument",
    description: "UNESCO Buddhist monument commissioned by Emperor Ashoka in 3rd century BCE.",
    latitude: 23.4793,
    longitude: 77.7397,
  },
  {
    id: "fm-mp-bhopal",
    name: "Bhopal",
    state: "Madhya Pradesh",
    stateCode: "MP",
    type: "city",
    category: "city",
    description: "Capital of Madhya Pradesh — gateway to Khajuraho and Sanchi.",
    latitude: 23.2599,
    longitude: 77.4126,
  },

  // ========== DELHI ==========
  {
    id: "fm-dl-redfort",
    name: "Red Fort",
    state: "Delhi",
    stateCode: "DL",
    type: "site",
    category: "monument",
    description: "UNESCO Mughal fortress-palace built by Shah Jahan in 1638.",
    latitude: 28.6562,
    longitude: 77.2410,
  },
  {
    id: "fm-dl-qutubminar",
    name: "Qutub Minar",
    state: "Delhi",
    stateCode: "DL",
    type: "site",
    category: "monument",
    description: "UNESCO tallest brick minaret at 72.5 meters, built starting 1192.",
    latitude: 28.5244,
    longitude: 77.1855,
  },
  {
    id: "fm-dl-humayun",
    name: "Humayun's Tomb",
    state: "Delhi",
    stateCode: "DL",
    type: "site",
    category: "monument",
    description: "UNESCO Mughal garden tomb — precursor to the Taj Mahal.",
    latitude: 28.5933,
    longitude: 77.2507,
  },
  {
    id: "fm-dl-delhi",
    name: "New Delhi",
    state: "Delhi",
    stateCode: "DL",
    type: "city",
    category: "city",
    description: "Capital of India — seven cities, centuries of history.",
    latitude: 28.6139,
    longitude: 77.2090,
  },

  // ========== LESSER-KNOWN HERITAGE ==========
  // Gujarat
  {
    id: "fm-gj-lothal",
    name: "Lothal",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "Indus Valley Civilization port city — one of the earliest known dockyards.",
    latitude: 22.5236,
    longitude: 72.2453,
  },
  {
    id: "fm-gj-champaner",
    name: "Champaner-Pavagadh",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "UNESCO World Heritage archaeological park with pre-Mughal Islamic city.",
    latitude: 22.4869,
    longitude: 73.5399,
  },
  {
    id: "fm-gj-palitana",
    name: "Palitana Temples",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "Over 900 Jain temples on Shatrunjaya hill — the largest cluster of temples in the world.",
    latitude: 21.5222,
    longitude: 71.8234,
  },
  {
    id: "fm-gj-diu",
    name: "Diu Fort",
    state: "Gujarat",
    stateCode: "GJ",
    type: "site",
    category: "monument",
    description: "Portuguese colonial fort on Diu island — coastal defense heritage.",
    latitude: 20.7140,
    longitude: 70.9873,
  },
  // Rajasthan
  {
    id: "fm-rj-chittorgarh",
    name: "Chittorgarh Fort",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "site",
    category: "monument",
    description: "Largest fort in India — symbol of Rajput courage and sacrifice.",
    latitude: 24.8887,
    longitude: 74.6269,
  },
  {
    id: "fm-rj-kumbhalgarh",
    name: "Kumbhalgarh Fort",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "site",
    category: "monument",
    description: "UNESCO site with the second-longest wall in the world — birthplace of Maharana Pratap.",
    latitude: 25.1483,
    longitude: 73.5482,
  },
  {
    id: "fm-rj-jaisalmer",
    name: "Jaisalmer Fort",
    state: "Rajasthan",
    stateCode: "RJ",
    type: "site",
    category: "monument",
    description: "Living fort in the Thar Desert — one of the few remaining inhabited forts.",
    latitude: 26.9124,
    longitude: 70.9126,
  },
  // Punjab
  {
    id: "fm-pb-wagah",
    name: "Wagah Border",
    state: "Punjab",
    stateCode: "PB",
    type: "site",
    category: "monument",
    description: "India-Pakistan border ceremony — daily flag-lowering ceremony.",
    latitude: 31.6047,
    longitude: 74.5728,
  },
  // Goa
  {
    id: "fm-ga-se-cathedral",
    name: "Church of St. Cajetan",
    state: "Goa",
    stateCode: "GA",
    type: "site",
    category: "monument",
    description: "Italian-style basilica in Old Goa — modeled after St. Peter's Basilica in Rome.",
    latitude: 15.5049,
    longitude: 73.9113,
  },
  // Tamil Nadu
  {
    id: "fm-tn-brihadeeswara",
    name: "Brihadeeswara Temple",
    state: "Tamil Nadu",
    stateCode: "TN",
    type: "site",
    category: "monument",
    description: "UNESCO Great Living Chola Temple — architectural marvel in Thanjavur.",
    latitude: 10.7828,
    longitude: 79.1318,
  },
  {
    id: "fm-tn-kanchipuram",
    name: "Kanchipuram",
    state: "Tamil Nadu",
    stateCode: "TN",
    type: "city",
    category: "city",
    description: "City of Temples — ancient Pallava and Chola heritage with silk weaving tradition.",
    latitude: 12.8342,
    longitude: 79.7036,
  },
  // Maharashtra
  {
    id: "fm-mh-raigad",
    name: "Raigad Fort",
    state: "Maharashtra",
    stateCode: "MH",
    type: "site",
    category: "monument",
    description: "Capital of Chhatrapati Shivaji Maharaj — Maratha empire stronghold.",
    latitude: 18.2345,
    longitude: 73.4485,
  },
  {
    id: "fm-mh-elephanta",
    name: "Elephanta Caves",
    state: "Maharashtra",
    stateCode: "MH",
    type: "site",
    category: "monument",
    description: "UNESCO cave complex on Elephanta Island — ancient Hindu rock-cut sculptures.",
    latitude: 18.9634,
    longitude: 72.9315,
  },
  // Madhya Pradesh
  {
    id: "fm-mp-bhimbetka",
    name: "Bhimbetka Rock Shelters",
    state: "Madhya Pradesh",
    stateCode: "MP",
    type: "site",
    category: "monument",
    description: "UNESCO prehistoric cave paintings spanning 30,000 years.",
    latitude: 23.9378,
    longitude: 77.6084,
  },
  {
    id: "fm-mp-orchha",
    name: "Orchha Heritage Town",
    state: "Madhya Pradesh",
    stateCode: "MP",
    type: "site",
    category: "monument",
    description: "Bundela Rajput heritage — palaces, temples, and cenotaphs along the Betwa River.",
    latitude: 25.3518,
    longitude: 78.6405,
  },
  // Delhi
  {
    id: "fm-dl-jama-masjid",
    name: "Jama Masjid",
    state: "Delhi",
    stateCode: "DL",
    type: "site",
    category: "monument",
    description: "India's largest mosque — built by Shah Jahan in 1656.",
    latitude: 28.6507,
    longitude: 77.2334,
  },
  {
    id: "fm-dl-pillar",
    name: "Iron Pillar",
    state: "Delhi",
    stateCode: "DL",
    type: "site",
    category: "monument",
    description: "1600-year-old rust-resistant iron pillar — metallurgical marvel of ancient India.",
    latitude: 28.5244,
    longitude: 77.1855,
  },

  // ========== KERALA ==========
  {
    id: "fm-kl-northmalabar",
    name: "North Malabar",
    state: "Kerala",
    stateCode: "KL",
    type: "site",
    category: "cultural_site",
    description: "North Malabar region — Theyyam rituals, sacred groves, and pristine waterfalls.",
    latitude: 11.87,
    longitude: 75.37,
  },
  {
    id: "fm-kl-wayanad",
    name: "Wayanad",
    state: "Kerala",
    stateCode: "KL",
    type: "site",
    category: "natural_landmark",
    description: "Hill district with waterfalls, caves, forests, and spice plantations.",
    latitude: 11.68,
    longitude: 76.13,
  },
  {
    id: "fm-kl-thiruvananthapuram",
    name: "Thiruvananthapuram",
    state: "Kerala",
    stateCode: "KL",
    type: "city",
    category: "city",
    description: "Capital of Kerala — Padmanabhaswamy Temple and cultural center.",
    latitude: 8.5241,
    longitude: 76.9366,
  },
  {
    id: "fm-kl-athirappilly",
    name: "Athirappilly Falls",
    state: "Kerala",
    stateCode: "KL",
    type: "site",
    category: "waterfall",
    description: "Majestic waterfall on the Chalakudy River — the Niagara of India.",
    latitude: 10.1734,
    longitude: 76.5508,
  },

  // ========== JAMMU & KASHMIR ==========
  {
    id: "fm-jk-gurez",
    name: "Gurez Valley",
    state: "Jammu & Kashmir",
    stateCode: "JK",
    type: "site",
    category: "cultural_site",
    description: "Pristine Himalayan valley — home to the Dard-Shina tribal community.",
    latitude: 34.68,
    longitude: 74.83,
  },
  {
    id: "fm-jk-dallake",
    name: "Dal Lake",
    state: "Jammu & Kashmir",
    stateCode: "JK",
    type: "site",
    category: "natural_landmark",
    description: "Iconic lake in Srinagar — houseboats, floating gardens, and Mughal heritage.",
    latitude: 34.1087,
    longitude: 74.8398,
  },
  {
    id: "fm-jk-srinagar",
    name: "Srinagar",
    state: "Jammu & Kashmir",
    stateCode: "JK",
    type: "city",
    category: "city",
    description: "Summer capital — Mughal gardens, Dal Lake, and Kashmiri culture.",
    latitude: 34.0837,
    longitude: 74.7973,
  },
  {
    id: "fm-jk-habbakhtoon",
    name: "Habba Khatoon Peak",
    state: "Jammu & Kashmir",
    stateCode: "JK",
    type: "site",
    category: "mountain",
    description: "Iconic pyramid-shaped peak in Gurez Valley, named after the Kashmiri poetess.",
    latitude: 34.70,
    longitude: 74.85,
  },

  // ========== ASSAM ==========
  {
    id: "fm-as-majuli",
    name: "Majuli",
    state: "Assam",
    stateCode: "AS",
    type: "site",
    category: "cultural_site",
    description: "World's largest inhabited river island — Satras, mask-making, and Sattriya dance.",
    latitude: 26.95,
    longitude: 94.15,
  },
  {
    id: "fm-as-kaziranga",
    name: "Kaziranga National Park",
    state: "Assam",
    stateCode: "AS",
    type: "site",
    category: "wildlife",
    description: "UNESCO site — home to two-thirds of the world's one-horned rhinoceros.",
    latitude: 26.6340,
    longitude: 93.3570,
  },
  {
    id: "fm-as-guwahati",
    name: "Guwahati",
    state: "Assam",
    stateCode: "AS",
    type: "city",
    category: "city",
    description: "Largest city in Assam — gateway to northeast India.",
    latitude: 26.1445,
    longitude: 91.7362,
  },

  // ========== ODISHA ==========
  {
    id: "fm-od-satkosia",
    name: "Satkosia Gorge",
    state: "Odisha",
    stateCode: "OD",
    type: "site",
    category: "natural_landmark",
    description: "Spectacular Mahanadi gorge through Eastern Ghats — tiger reserve with gharials.",
    latitude: 20.72,
    longitude: 84.78,
  },
  {
    id: "fm-od-konark",
    name: "Konark Sun Temple",
    state: "Odisha",
    stateCode: "OD",
    type: "site",
    category: "monument",
    description: "UNESCO 13th-century Sun Temple — masterpiece of Kalinga architecture.",
    latitude: 19.8876,
    longitude: 86.0945,
  },
  {
    id: "fm-od-puri",
    name: "Puri",
    state: "Odisha",
    stateCode: "OD",
    type: "city",
    category: "city",
    description: "Sacred city — Jagannath Temple and one of the Char Dham pilgrimage sites.",
    latitude: 19.8135,
    longitude: 85.8312,
  },
  {
    id: "fm-od-bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    stateCode: "OD",
    type: "city",
    category: "city",
    description: "Temple City — Lingaraj Temple and ancient Kalinga heritage.",
    latitude: 20.2961,
    longitude: 85.8245,
  },
  {
    id: "fm-od-mahanadi",
    name: "Mahanadi River",
    state: "Odisha",
    stateCode: "OD",
    type: "site",
    category: "river",
    description: "Major river of India forming the Satkosia Gorge through the Eastern Ghats.",
    latitude: 20.50,
    longitude: 85.00,
  },
];

/**
 * Get famous markers for a specific state.
 */
export function getFamousMarkersForState(stateCode: string): FamousMarker[] {
  return FAMOUS_HERITAGE_MARKERS.filter((m) => m.stateCode === stateCode);
}

/**
 * Get all famous markers.
 */
export function getAllFamousMarkers(): FamousMarker[] {
  return FAMOUS_HERITAGE_MARKERS;
}
